### ISSUE TITLE
Browser icon always fails to update when turning DND on

### ISSUE THREAD

**Issue by WillDeStijl** [refactorsaurusrex/ChromeDND#17]
My browser icon fails to update ever at all.

I've turned it on for the first time & got the same, dim icon.
Tried:
 - turning on & off, waiting 2 - 3 seconds between ons and offs
 - waiting longer between on/off
 - tried different time ranges & switching between them, waiting various amounts of time

Google Chrome is up to date
Version 66.0.3359.139 (Official Build) (64-bit)
on Windows 10 Home

**Comment by refactorsaurusrex** [comment]
Thanks for the information. This extension is definitely in need of some love. I hope to get to it soon.

**Comment by refactorsaurusrex** [comment]
@WillDeStijl I just released [v0.5.1][0]. Give it a try and let me know if this issue persists. Thanks!

[0]: https://github.com/refactorsaurusrex/ChromeDND/releases/tag/v0.5.1
