### ISSUE TITLE
History

### ISSUE THREAD

**Issue by orschiro** [refactorsaurusrex/ChromeDND#19]
Is there a history of all notifications that had occurred during "do not disturb"?

**Comment by refactorsaurusrex** [comment]
Hey @orschiro, history is not tracked, no. The extension just turns off all notifications when DND is active and then turns them back on again after DND ends.

**Comment by orschiro** [comment]
Which is quite useful! Do you have any idea how to track missed
notifications?

-

**Comment by refactorsaurusrex** [comment]
I really don't think it's possible from an end user's prospective. Once the notifications are disabled, they're just off and there's nothing to track. It *might* be possible with code by hooking the notifications pipeline (if there is such a concept in the Chrome API - this is a total guess), suppressing the notification, and then, finally, relaying them all to the user once DND ends.

**Comment by orschiro** [comment]
Ok let me know. I'm happy to report it upstream if the api is missing
something! ☺️👍

-

**Comment by refactorsaurusrex** [comment]
> Ok let me know.

To be clear, this isn't something I will be doing myself, but I'll happily accept a pull request from someone else! ;)
